### ISSUE TITLE
About the construction method of the pos and neg dataset

### ISSUE THREAD

**Issue by jams-xin** [DAMO-NLP-SG/LLM-R2#2]
Hello,  I couldn't find the method to generate  the dataset of the pools directory  in the code (such as: neg_pool-d sb_clean. csv, neg_pool-d sb_upped. csv, pos_pool-d sb_clean. csv, pos_pool-d sb_upped. csv) , may I ask how are the datasets constructed.  Thank you very much.

**Comment by LZ12DH** [comment]
Hi! Sorry for late reply. For pool cleaning we just remove the duplicates and we have uploaded a cleaning script into the dir. Thanks for point this out!
